kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: minecraft-pvc
  annotations:
#    trident.netapp.io/reclaimPolicy: "Delete"
    trident.netapp.io/snapshotPolicy: "default-1weekly"
#    trident.netapp.io/protocol: "file"
    trident.netapp.io/snapshotDirectory: "true"
#    trident.netapp.io/unixPermissions: "---rwxrwxrwx"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ontap-gold
